name: CI

on: 
  push: 
    branches:
      - main

jobs: 
  build-and-push: 
    name: 'Build and Push'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate SHA
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Login to docker hub container registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build docker image
        run: docker build -t dsllt/nlw-journey-devops:${{ steps.generate_sha.outputs.sha }} .

      - name: Push docker image
        run: |
          docker push dsllt/nlw-journey-devops:${{ steps.generate_sha.outputs.sha }} .
          docker tag dsllt/nlw-journey-devops:${{ steps.generate_sha.outputs.sha }} dsllt/nlw-journey-devops:latest
          docker push dsllt/nlw-journey-devops:latest